stages:
  - docker_pre_clean
  - make
  - docker_post_clean

docker_pre_clean:
  stage: docker_pre_clean
  script:
    - ${CI_PROJECT_DIR}/BuildServer/Docker/clean.sh
  allow_failure: true
  tags:
    - docker
    - sci
    - ubuntu

docker_post_clean:
  stage: docker_post_clean
  script:
    - ${CI_PROJECT_DIR}/BuildServer/Docker/clean.sh
  allow_failure: true
  when: always
  dependencies: []
  tags:
    - docker
    - sci
    - ubuntu
#===============

make:linux_gfortran:
  stage: make
  script:
    - docker build --force-rm -t ci_crysfml_xenial_gfortran -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_setup_xenial_gfortran .
    - docker build --force-rm --no-cache -t ci_crysfml_xenial_gfortran_build -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_build_xenial_gfortran --build-arg CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA} --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} .
    - docker run -iv${PWD}:/artifacts/ ci_crysfml_xenial_gfortran_build
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/build_gfortran
    expire_in: 1 day
  tags:
    - docker
    - sci
    - ubuntu
    
make:linux_ifort:
  stage: make
  script:
    - docker build --force-rm -t ci_crysfml_xenial_ifort -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_setup_xenial_ifort .
    - docker build --force-rm --no-cache -t ci_crysfml_xenial_ifort_build -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_build_xenial_ifort --build-arg CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA} --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} .
    - docker run -i -v${PWD}:/artifacts/ -v/users/ci/projects/fullprof/intel:/opt/intel -v/users/ci/projects/fullprof/hdf5-1_12_0:/hdf5 ci_crysfml_xenial_ifort_build
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/build_ifort
    expire_in: 1 day
  tags:
    - docker
    - sci
    - ubuntu
    
#===============

make:macos_gfortran:
  stage: make
  script:
    - export HDF5_INCLUDE_PATH="/Users/ci/Projects/fullprof/hdf5-gfortran/include"
    - export HDF5_LIBRARY_PATH="/Users/ci/Projects/fullprof/hdf5-gfortran/lib"
    - BuildServer/Unix/build.sh gfortran
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/build_gfortran
    expire_in: 1 day
  tags:
    - sci
    - osx-10.13
    
make:macos_ifort:
  stage: make
  script:
    - export HDF5_INCLUDE_PATH="/Users/ci/Projects/fullprof/hdf5-ifort/include"
    - export HDF5_LIBRARY_PATH="/Users/ci/Projects/fullprof/hdf5-ifort/lib"
    - BuildServer/Unix/build.sh ifort
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/build_ifort
    expire_in: 1 day
  tags:
    - sci
    - osx-10.13   

#===============

make:windows_gfortran:
  stage: make
  script:
    - set PATH=%PATH:C:\Program Files\Git\bin;=%
    - set HDF5_INCLUDE_PATH=C:\\Projects\\fullprof\\hdf5-gfortran\\include
    - set HDF5_LIBRARY_PATH=C:\\Projects\\fullprof\\hdf5-gfortran\\lib
    - call "BuildServer\\Windows\\build.bat" gfortran
  artifacts:
    paths:
    - "%CI_PROJECT_DIR%\\build_gfortran"
    expire_in: 1 day
  tags:
    - sci
    - windows-10
    
make:windows_ifort:
  stage: make
  script:
    - call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
    - set LIB="C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.3.203\\windows\\compiler\\lib\\intel64_win";%LIB%
    - set HDF5_INCLUDE_PATH=C:\\Projects\\fullprof\\hdf5-ifort\\include\\shared
    - set HDF5_LIBRARY_PATH=C:\\Projects\\fullprof\\hdf5-ifort\\lib
    - call "BuildServer\\Windows\\build.bat" ifort
  artifacts:
    paths:
    - "%CI_PROJECT_DIR%\\build_ifort"
    expire_in: 1 day
  tags:
    - sci
    - windows-10