stages:
  - docker_pre_clean
  - make
  - make_release
  - docker_post_clean

docker_pre_clean:
  stage: docker_pre_clean
  script:
    - ${CI_PROJECT_DIR}/BuildServer/Docker/clean.sh
  allow_failure: true
  tags:
    - docker
    - sci
    - ubuntu

docker_post_clean:
  stage: docker_post_clean
  script:
    - ${CI_PROJECT_DIR}/BuildServer/Docker/clean.sh
  allow_failure: true
  when: always
  dependencies: []
  tags:
    - docker
    - sci
    - ubuntu
    
#===============
#== MAKE SECTION
#===============

make:linux_gfortran:
  stage: make
  script:
    - docker build --force-rm -t ci_crysfml_xenial_gfortran -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_xenial_gfortran_setup .
    - docker build --force-rm --no-cache -t ci_crysfml_xenial_gfortran_build -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_xenial_gfortran_build --build-arg CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA} --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} .
    - docker run -iv${PWD}:/artifacts/ ci_crysfml_xenial_gfortran_build
  tags:
    - docker
    - sci
    - ubuntu
    
make:linux_ifort:
  stage: make
  script:
    - docker build --force-rm -t ci_crysfml_xenial_ifort -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_xenial_ifort_setup .
    - docker build --force-rm --no-cache -t ci_crysfml_xenial_ifort_build -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_xenial_ifort_build --build-arg CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA} --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} .
    - docker run -i -v${PWD}:/artifacts/ -v/users/ci/projects/fullprof/intel:/opt/intel -v/users/ci/projects/fullprof/hdf5-1_12_0:/hdf5 ci_crysfml_xenial_ifort_build
  tags:
    - docker
    - sci
    - ubuntu

make:linux_gfortran_F2008:
  stage: make
  script:
    - docker build --force-rm -t ci_crysfml_xenial_gfortran_f2008 -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_xenial_gfortran_setup_F2008 .
    - docker build --force-rm --no-cache -t ci_crysfml_xenial_gfortran_build_f2008 -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_xenial_gfortran_build_F2008 --build-arg CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA} --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} .
    - docker run -iv${PWD}:/artifacts/ ci_crysfml_xenial_gfortran_build_f2008
  tags:
    - docker
    - sci
    - ubuntu
    
make:linux_ifort_F2008:
  stage: make
  script:
    - docker build --force-rm -t ci_crysfml_xenial_ifort -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_xenial_ifort_setup .
    - docker build --force-rm --no-cache -t ci_crysfml_xenial_ifort_build_f2008 -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_xenial_ifort_build_F2008 --build-arg CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA} --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} .
    - docker run -i -v${PWD}:/artifacts/ -v/users/ci/projects/fullprof/intel:/opt/intel ci_crysfml_xenial_ifort_build_f2008
  tags:
    - docker
    - sci
    - ubuntu

#===============

make:macos_gfortran:
  stage: make
  script:
    - export HDF5_INCLUDE_PATH="/Users/ci/Projects/fullprof/hdf5-gfortran/include"
    - export HDF5_LIBRARY_PATH="/Users/ci/Projects/fullprof/hdf5-gfortran/lib"
    - BuildServer/Unix/build.sh gfortran
  tags:
    - sci
    - osx-10.13
    
make:macos_ifort:
  stage: make
  script:
    - export HDF5_INCLUDE_PATH="/Users/ci/Projects/fullprof/hdf5-ifort/include"
    - export HDF5_LIBRARY_PATH="/Users/ci/Projects/fullprof/hdf5-ifort/lib"
    - BuildServer/Unix/build.sh ifort
  tags:
    - sci
    - osx-10.13

make:macos_gfortran_F2008:
  stage: make
  script:
    - BuildServer/Unix/build_F2008.sh gfortran
  tags:
    - sci
    - osx-10.13

make:macos_ifort_F2008:
  stage: make
  script:
    - BuildServer/Unix/build_F2008.sh ifort
  tags:
    - sci
    - osx-10.13

#===============

make:windows_gfortran:
  stage: make
  script:
    - set PATH=%PATH:C:\Program Files\Git\bin;=%
    - set HDF5_INCLUDE_PATH=C:\\Projects\\fullprof\\hdf5-gfortran\\include
    - set HDF5_LIBRARY_PATH=C:\\Projects\\fullprof\\hdf5-gfortran\\lib
    - call "BuildServer\\Windows\\build.bat" gfortran
  tags:
    - sci
    - windows-10

make:windows_ifort:
  stage: make
  script:
    - call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
    - set LIB="C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.3.203\\windows\\compiler\\lib\\intel64_win";%LIB%
    - set HDF5_INCLUDE_PATH=C:\\Projects\\fullprof\\hdf5-ifort\\include\\shared
    - set HDF5_LIBRARY_PATH=C:\\Projects\\fullprof\\hdf5-ifort\\lib
    - call "BuildServer\\Windows\\build.bat" ifort
  tags:
    - sci
    - windows-10

make:windows_gfortran_F2008:
  stage: make
  script:
    - set PATH=%PATH:C:\Program Files\Git\bin;=%
    - set PATH=%PATH:c:\Projects\fullprof\mingw\bin;=%
    - set PATH=c:\Projects\fullprof\MinGW64\bin;%PATH%
    - call "BuildServer\\Windows\\build_F2008.bat" gfortran
  tags:
    - sci
    - windows-10

make:windows_ifort_F2008:
  stage: make
  script:
    - call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
    - set LIB="C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.3.203\\windows\\compiler\\lib\\intel64_win";%LIB%
    - call "BuildServer\\Windows\\build_F2008.bat" ifort
  tags:
    - sci
    - windows-10
    
#=======================
#== MAKE RELEASE SECTION
#=======================

make_release:linux:
  stage: make_release
  script:
    - docker build --force-rm -t ci_crysfml_xenial_ifort -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_xenial_ifort_setup .
    - docker build --force-rm --no-cache -t ci_crysfml_xenial_release_build -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_xenial_release_build --build-arg CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA} --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} .
    - docker run -i -v${PWD}:/artifacts/ -v/users/ci/projects/fullprof/intel:/opt/intel -v/users/ci/projects/fullprof/hdf5-1_12_0:/hdf5 ci_crysfml_xenial_release_build
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/build_release
    expire_in: 1 day
  tags:
    - docker
    - sci
    - ubuntu

make_release:linux_F2008:
  stage: make_release
  script:
    - docker build --force-rm -t ci_crysfml_xenial_ifort -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_xenial_ifort_setup .
    - docker build --force-rm --no-cache -t ci_crysfml_xenial_release_build_f2008 -f ${CI_PROJECT_DIR}/BuildServer/Docker/Dockerfile_xenial_release_build_F2008 --build-arg CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA} --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} .
    - docker run -i -v${PWD}:/artifacts/ -v/users/ci/projects/fullprof/intel:/opt/intel ci_crysfml_xenial_release_build_f2008
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/build_release_F2008
    expire_in: 1 day
  tags:
    - docker
    - sci
    - ubuntu

#===============
make_release:macos:
  stage: make_release
  script:
    - export HDF5_INCLUDE_PATH="/Users/ci/Projects/fullprof/hdf5-ifort/include"
    - export HDF5_LIBRARY_PATH="/Users/ci/Projects/fullprof/hdf5-ifort/lib"
    - BuildServer/Unix/build_release.sh
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/build_release
    expire_in: 1 day
  tags:
    - sci
    - osx-10.13

make_release:macos_F2008:
  stage: make_release
  script:
    - BuildServer/Unix/build_release_F2008.sh
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/build_release_F2008
    expire_in: 1 day
  tags:
    - sci
    - osx-10.13

#===============

make_release:windows:
  stage: make_release
  script:
    - call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
    - set LIB="C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.3.203\\windows\\compiler\\lib\\intel64_win";%LIB%
    - set HDF5_INCLUDE_PATH=C:\\Projects\\fullprof\\hdf5-ifort\\include\\shared
    - set HDF5_LIBRARY_PATH=C:\\Projects\\fullprof\\hdf5-ifort\\lib
    - call "BuildServer\\Windows\\build_release.bat"
  artifacts:
    paths:
    - "%CI_PROJECT_DIR%\\build_release"
    expire_in: 1 day
  tags:
    - sci
    - windows-10

make_release:windows_F2008:
  stage: make_release
  script:
    - call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
    - set LIB="C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.3.203\\windows\\compiler\\lib\\intel64_win";%LIB%
    - call "BuildServer\\Windows\\build_release_F2008.bat"
  artifacts:
    paths:
    - "%CI_PROJECT_DIR%\\build_release_F2008"
    expire_in: 1 day
  tags:
    - sci
    - windows-10