# Adapted from https://github.com/RalfG/python-wheels-manylinux-build/blob/master/full_workflow_example.yml
name: Build and (soon Publish Linux Python packages)

on:
  push:
    branches: [ simon ]

jobs:
  create-Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install python dependencies
      run: |
       python -m pip install --upgrade pip
       python -m pip install twine
    - name: Build manylinux wheels
      uses: RalfG/python-wheels-manylinux-build@v0.2.2-manylinux2010_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp310-cp310'
        build-requirements: 'cmake'
        system-packages: ''
        package-path: ''
        pip-wheel-args: '-w ./dist'
    - uses: actions/upload-artifact@v2
      with:
        name: CrysFML - Linux
        path: ${{ github.workspace }}/dist/*
  create-OSX:

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [macos-10.15, macos-11.0]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python-version}}

    - name: Set Compiler (OSX)
      run: |
        echo "FC=gfortran-9" >> $GITHUB_ENV
        echo "CC=gcc-9" >> $GITHUB_ENV

    - name: Install cmake
      run: pip3 install cmake

    - name: Build CFML
      run: pip wheel ./ --no-deps -w ./dist/

    - uses: actions/upload-artifact@v2
      with:
        name: CrysFML - OSX
        path: ${{ github.workspace }}/dist/*