# Adapted from https://github.com/RalfG/python-wheels-manylinux-build/blob/master/full_workflow_example.yml
name: Build and (soon Publish Linux Python packages)

on:
  push:
    branches: [ simon ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install python dependencies
      run: |
       python -m pip install --upgrade pip
       python -m pip install twine
    - name: Build manylinux wheels
      uses: RalfG/python-wheels-manylinux-build@v0.2.2-manylinux2010_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38'
        build-requirements: 'cmake'
        system-packages: ''
        package-path: ''
        pip-wheel-args: '-w ./dist'
    - uses: actions/upload-artifact@v2
      with:
        name: CrysFML
        path: ${{ github.workspace }}/dist/*